# Generated by Django 2.2 on 2020-12-27 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20201227_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image_url',
        ),
        migrations.DeleteModel(
            name='URL',
        ),
    ]
